FROM node:18-alpine

WORKDIR /app

# The node_modules might be volume mounted, but we'll install dependencies globally or locally just in case
COPY package*.json ./
RUN npm install

COPY . .

# Expose port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
